{%mainunit gfx_constants.pas}

rsLanguage               = 'Español';


// Buttons
rsOK                     = 'Aceptar';
rsCancel                 = 'Cancelar';
rsHelp                   = 'Ayuda';
rsOpen                   = 'Abrir';
rsSave                   = 'Guardar';
rsCreate                 = 'Crear';
rsChange                 = 'Cambiar';
rsFind                   = 'Buscar';
rsSearch                 = 'Buscar';
rsReplace                = 'Reemplazar';
rsConfirm                = 'Confirmar';
rsAll                    = 'Todos';
rsSelect                 = 'Seleccionar';
rsYes                    = 'Si';
rsNo                     = 'No';
rsAbort                  = 'Abortar';
rsRetry                  = 'Reintentar';
rsIgnore                 = 'Ignorar';
rsClose                  = 'Cerrar';


// General messages
rsNewItemDetected       = 'A new item has been detected.';
rsAddNewItem            = 'Would you like to add the new item <%s> to the list?';
rsInsert                 = 'Insertar';
rsEdit                   = 'Editar';
rsDelete                 = 'Borrar';
rsExit                   = 'Salir';
rsYesToAll               = 'Si a Todo';
rsNoToAll                = 'No a Todo';
rsCut                    = 'Cortar';
rsCopy                   = 'Copiar';
rsPaste                  = 'Pegar';


// Captions
rsError                  = 'Error';
rsCriticalError          = 'Error Crítico';
rsInformation            = 'Información';
rsConfirmation           = 'Confirmación';
rsWarning                = 'Advertencia';
rsMessage                = 'Mensaje';
rsAbout                  = 'Acerca de %s';


// Standard file filters
rsAllFiles               = 'Todos los Archivos';


// CreateDir Dialog
rsCreateDirectory        = 'Crear carpeta';
rsEnterNewDirectory      = 'Ingrese el nombre de la carpeta nueva';
rsCannotCreateDir        = 'No se puede crear la carpeta';


// Font Dialog
rsSelectAFont            = 'Seleccione una fuente';
rsName                   = 'Nombre';
rsCollection             = 'Colección';
rsSize                   = 'Tamaño';
rsStyle                  = 'Estilo';
rsItalic                 = 'Italica';
rsBold                   = 'Negrita';
rsUnderScore             = 'Subrayado';
rsTypeface               = 'Typeface';
rsAntiAliasing           = 'Anti aliasing';
rsExampleText            = 'Texto de Ejemplo';
rsCollectionAllFonts     = 'Todas las Fuentes';
rsCollectionRecentlyUsed = 'Usados Recientemente';
rsCollectionFavourites   = 'Favoritos';
rsCollectionFixedWidth   = 'Ancho Fijo';
rsCollectionSans         = 'Sans';
rsCollectionSerif        = 'Serif';
rsCollectionFontAliases  = 'Aliases de Fuentes';


// Open Dialog
rsOpenAFile              = 'Abrir un archivo';
rsFileName               = 'Nombre de archivo';
rsFileType               = 'Tipo de archivo';
rsDrive                  = 'Unidad';
rsFiles                  = 'Archivos';
rsDirectories            = 'Carpetas';
rsShowHidden             = 'Mostrar archivos ocultos';
rsFileSelection          = 'Selección de Archivo';
rsFileModifiedTime       = 'Hora de Modif.';
rsFileAttributes         = 'Atributos';
rsFileRights             = 'Derechos';
rsFileOwner              = 'Dueño';
rsFileGroup              = 'Grupo';


// Save Dialog
rsSaveAFile              = 'Guardar como';


// User Dialog
rsUserName               = 'Nombre de usuario';
rsPassword               = 'Contraseña';
rsDatabase               = 'Base de datos';


// Error messages
rsErrListMustBeEmpty     = 'La lista debe estar vacia';
rsErrCouldNotOpenDir     = 'No se puede abrir la carpeta <%s>';
rsErrItemOfWrongType     = 'El item no es del tipo <%s>!';
rsErrFailedToCreateDir   = 'No se ha podido crear la carpeta <%s>';
rsErrNotAssigned         = '<%s> no está asignado';


// Calendar Combo & Dialog
rsShortMon               = 'Lun';
rsShortTue               = 'Mar';
rsShortWed               = 'Mie';
rsShortThu               = 'Jun';
rsShortFri               = 'Vie';
rsShortSat               = 'Sab';
rsShortSun               = 'Dom';
rsLongMon                = 'Lunes';
rsLongTue                = 'Martes';
rsLongWed                = 'Miércoles';
rsLongThu                = 'Jueves';
rsLongFri                = 'Viernes';
rsLongSat                = 'Sábado';
rsLongSun                = 'Domingo';
rsToday                  = 'Today';
rsShortJan               = 'Jan';
rsShortFeb               = 'Feb';
rsShortMar               = 'Mar';
rsShortApr               = 'Apr';
rsShortMay               = 'May';
rsShortJun               = 'Jun';
rsShortJul               = 'Jul';
rsShortAug               = 'Aug';
rsShortSep               = 'Sep';
rsShortOct               = 'Oct';
rsShortNov               = 'Nov';
rsShortDec               = 'Dec';
rsLongJan                = 'January';
rsLongFeb                = 'February';
rsLongMar                = 'March';
rsLongApr                = 'April';
rsLongMay                = 'May';
rsLongJun                = 'June';
rsLongJul                = 'July';
rsLongAug                = 'August';
rsLongSep                = 'September';
rsLongOct                = 'October';
rsLongNov                = 'November';
rsLongDec                = 'December';




// General messages
rsNewItemDetected       = 'A new item has been detected.';
rsAddNewItem            = 'Would you like to add the new item <%s> to the list?';

