{%mainunit gfx_constants.pas}

rsLanguage               = 'Italian';


// Buttons
rsOK                     = 'OK';
rsCancel                 = 'Annulla';
rsHelp                   = 'Aiuto';
rsOpen                   = 'Apri';
rsSave                   = 'Salva';
rsCreate                 = 'Crea';
rsChange                 = 'Cambia';
rsFind                   = 'Trova';
rsSearch                 = 'Cerca';
rsReplace                = 'Sostituisci';
rsConfirm                = 'Conferma';
rsAll                    = 'Tutto';
rsSelect                 = 'Seleziona';
rsYes                    = 'Sì';
rsNo                     = 'No';
rsAbort                  = 'Interrompi';
rsRetry                  = 'Riprova';
rsIgnore                 = 'Ignora';
rsClose                  = 'Chiudi';
rsInsert                 = 'Inserisci';
rsEdit                   = 'Modifica';
rsDelete                 = 'Cancella';
rsExit                   = 'Esci';
rsYesToAll               = 'Sì a Tutto';
rsNoToAll                = 'No a Tutto';


// Captions
rsError                  = 'Errore';
rsCriticalError          = 'Errore Critico';
rsInformation            = 'Informazione';
rsConfirmation           = 'Conferma';
rsWarning                = 'Attenzione';
rsMessage                = 'Messaggio';


// Standard file filters
rsAllFiles               = 'Tutti i Files';


// CreateDir Dialog
rsCreateDirectory        = 'Crea cartella';
rsEnterNewDirectory      = 'Inserisci nuovo nome della cartella';
rsCannotCreateDir        = 'Non riesco a creare la cartella';


// Font Dialog
rsSelectAFont            = 'Seleziona un font';
rsName                   = 'Nome';
rsCollection             = 'Collezione';
rsSize                   = 'Dimensione';
rsStyle                  = 'Stile';
rsItalic                 = 'Italico';
rsBold                   = 'Grassetto';
rsUnderScore             = 'Sottolineato';
rsExampleText            = 'Testo di Esempio';


// Open Dialog
rsOpenAFile              = 'Apri un file';
rsFileName               = 'Nome del file';
rsFileType               = 'Tipo di file';
rsDrive                  = 'Disco';
rsFiles                  = 'Files';
rsDirectories            = 'Cartelle';
rsShowHidden             = 'Mostra files nascosti';


// Save Dialog
rsSaveAFile              = 'Salva con nome';


