{%mainunit gfx_constants.pas}

rsLanguage               = 'Italiano';


// Buttons
rsOK                     = 'OK';
rsCancel                 = 'Annulla';
rsHelp                   = 'Aiuto';
rsOpen                   = 'Apri';
rsSave                   = 'Salva';
rsCreate                 = 'Crea';
rsChange                 = 'Cambia';
rsFind                   = 'Trova';
rsSearch                 = 'Cerca';
rsReplace                = 'Sostituisci';
rsConfirm                = 'Conferma';
rsAll                    = 'Tutto';
rsSelect                 = 'Seleziona';
rsYes                    = 'Sì';
rsNo                     = 'No';
rsAbort                  = 'Interrompi';
rsRetry                  = 'Riprova';
rsIgnore                 = 'Ignora';
rsClose                  = 'Chiudi';
rsInsert                 = 'Inserisci';
rsEdit                   = 'Modifica';
rsDelete                 = 'Cancella';
rsExit                   = 'Esci';
rsYesToAll               = 'Sì a Tutto';
rsNoToAll                = 'No a Tutto';
rsCut                    = 'Taglia';
rsCopy                   = 'Copia';
rsPaste                  = 'Incolla';


// Captions
rsError                  = 'Errore';
rsCriticalError          = 'Errore Critico';
rsInformation            = 'Informazione';
rsConfirmation           = 'Conferma';
rsWarning                = 'Attenzione';
rsMessage                = 'Messaggio';
rsAbout                  = 'Informazioni %s';


// Standard file filters
rsAllFiles               = 'Tutti i Files';


// CreateDir Dialog
rsCreateDirectory        = 'Crea cartella';
rsEnterNewDirectory      = 'Inserisci nuovo nome della cartella';
rsCannotCreateDir        = 'Non riesco a creare la cartella';


// Font Dialog
rsSelectAFont            = 'Seleziona un font';
rsName                   = 'Nome';
rsCollection             = 'Collezione';
rsSize                   = 'Dimensione';
rsStyle                  = 'Stile';
rsItalic                 = 'Italico';
rsBold                   = 'Grassetto';
rsUnderScore             = 'Sottolineato';
rsTypeface               = 'Typeface';
rsAntiAliasing           = 'Anti aliasing';
rsExampleText            = 'Testo di Esempio';
rsCollectionAllFonts     = 'Tutti i Fonts';
rsCollectionRecentlyUsed = 'Usati Recentemente';
rsCollectionFavourites   = 'Preferiti';
rsCollectionFixedWidth   = 'Larghezza Fissa';
rsCollectionSans         = 'Sans';
rsCollectionSerif        = 'Serif';
rsCollectionFontAliases  = 'Font Aliases';


// Open Dialog
rsOpenAFile              = 'Apri un file';
rsFileName               = 'Nome del file';
rsFileType               = 'Tipo di file';
rsDrive                  = 'Disco';
rsFiles                  = 'Files';
rsDirectories            = 'Cartelle';
rsShowHidden             = 'Mostra files nascosti';
rsFileSelection          = 'Seleziona File';
rsFileModifiedTime       = 'Tempo Mod.';
rsFileAttributes         = 'Attributi';
rsFileRights             = 'Diritti';
rsFileOwner              = 'Proprietario';
rsFileGroup              = 'Gruppo';


// Save Dialog
rsSaveAFile              = 'Salva con nome';


// User Dialog
rsUserName               = 'Nome utente';
rsPassword               = 'Password';
rsDatabase               = 'Archivi';


// Error messages
rsErrListMustBeEmpty     = 'Elenco deve essere vuoto';
rsErrCouldNotOpenDir     = 'Impossibile aprire la cartella <%s>';
rsErrItemOfWrongType     = 'L''elemento non è del tipo <%s> !';
rsErrFailedToCreateDir   = 'Impossibile creare la cartella <%s>';
rsErrNotAssigned         = '<%s> non assegnato';


// Calendar Combo & Dialog
rsShortMon               = 'Lun';
rsShortTue               = 'Mar';
rsShortWed               = 'Mer';
rsShortThu               = 'Gio';
rsShortFri               = 'Ven';
rsShortSat               = 'Sab';
rsShortSun               = 'Dom';
rsLongMon                = 'Lunedì';
rsLongTue                = 'Martedì';
rsLongWed                = 'Mercoledì';
rsLongThu                = 'Giovedì';
rsLongFri                = 'Venerdì';
rsLongSat                = 'Sabato';
rsLongSun                = 'Domenica';
rsToday                  = 'Oggi';
rsShortJan               = 'Gen';
rsShortFeb               = 'Feb';
rsShortMar               = 'Mar';
rsShortApr               = 'Apr';
rsShortMay               = 'Mag';
rsShortJun               = 'Giu';
rsShortJul               = 'Lug';
rsShortAug               = 'Ago';
rsShortSep               = 'Set';
rsShortOct               = 'Ott';
rsShortNov               = 'Nov';
rsShortDec               = 'Dic';
rsLongJan                = 'Gennaio';
rsLongFeb                = 'Febbraio';
rsLongMar                = 'Marzo';
rsLongApr                = 'Aprile';
rsLongMay                = 'Maggio';
rsLongJun                = 'Giugno';
rsLongJul                = 'Luglio';
rsLongAug                = 'Agosto';
rsLongSep                = 'Settembre';
rsLongOct                = 'Ottobre';
rsLongNov                = 'Novembre';
rsLongDec                = 'Dicembre';

// General messages
rsNewItemDetected       = 'E'' stato rilevato un nuovo elemento.';
rsAddNewItem            = 'Vorresti aggiungere il nuovo elemento <%s> alla lista?';


