{%mainunit gfx_constants.pas}

rsLanguage               = 'Español';


// Buttons
rsOK                     = 'Aceptar';
rsCancel                 = 'Cancelar';
rsHelp                   = 'Ayuda';
rsOpen                   = 'Abrir';
rsSave                   = 'Guardar';
rsCreate                 = 'Crear';
rsChange                 = 'Cambiar';
rsFind                   = 'Buscar';
rsSearch                 = 'Buscar';
rsReplace                = 'Reemplazar';
rsConfirm                = 'Confirmar';
rsAll                    = 'Todos';
rsSelect                 = 'Seleccionar';
rsYes                    = 'Si';
rsNo                     = 'No';
rsAbort                  = 'Abortar';
rsRetry                  = 'Reintentar';
rsIgnore                 = 'Ignorar';
rsClose                  = 'Cerrar';
rsInsert                 = 'Insertar';
rsEdit                   = 'Editar';
rsDelete                 = 'Borrar';
rsExit                   = 'Salir';
rsYesToAll               = 'Si a Todo';
rsNoToAll                = 'No a Todo';
rsCut                    = 'Cut';
rsCopy                   = 'Copy';
rsPaste                  = 'Paste';


// Captions
rsError                  = 'Error';
rsCriticalError          = 'Error Crítico';
rsInformation            = 'Información';
rsConfirmation           = 'Confirmación';
rsWarning                = 'Advertencia';
rsMessage                = 'Mensaje';
rsAbout                  = 'About %s';


// Standard file filters
rsAllFiles               = 'Todos los Archivos';


// CreateDir Dialog
rsCreateDirectory        = 'Crear carpeta';
rsEnterNewDirectory      = 'Ingrese el nombre de la carpeta nueva';
rsCannotCreateDir        = 'No se puede crear la carpeta';


// Font Dialog
rsSelectAFont            = 'Seleccione una fuente';
rsName                   = 'Nombre';
rsCollection             = 'Colección';
rsSize                   = 'Tamaño';
rsStyle                  = 'Estilo';
rsItalic                 = 'Italica';
rsBold                   = 'Negrita';
rsUnderScore             = 'Subrayado';
rsTypeface               = 'Typeface';
rsAntiAliasing           = 'Anti aliasing';
rsExampleText            = 'Texto de Ejemplo';
rsCollectionAllFonts     = 'All Fonts';
rsCollectionRecentlyUsed = 'Recently Used';
rsCollectionFavourites   = 'Favourites';
rsCollectionFixedWidth   = 'Fixed Width';
rsCollectionSans         = 'Sans';
rsCollectionSerif        = 'Serif';
rsCollectionFontAliases  = 'Font Aliases';


// Open Dialog
rsOpenAFile              = 'Abrir un archivo';
rsFileName               = 'Nombre de archivo';
rsFileType               = 'Tipo de archivo';
rsDrive                  = 'Unidad';
rsFiles                  = 'Archivos';
rsDirectories            = 'Carpetas';
rsShowHidden             = 'Mostrar archivos ocultos';
rsFileSelection          = 'File Selection';
rsFileModifiedTime       = 'Mod. Time';
rsFileAttributes         = 'Attributes';
rsFileRights             = 'Rights';
rsFileOwner              = 'Owner';
rsFileGroup              = 'Group';


// Save Dialog
rsSaveAFile              = 'Guardar como';


// Error messages
rsErrListMustBeEmpty     = 'La lista debe estar vacia';
rsErrCouldNotOpenDir     = 'Could not open the directory <%s>';
rsErrItemOfWrongType     = 'Item is not of <%s> type!';
rsErrFailedToCreateDir   = 'Failed to create the directory <%s>';
rsErrNotAssigned         = '<%s> not assigned';


// Calendar Combo & Dialog
rsShortMon               = 'Mon';
rsShortTue               = 'Tue';
rsShortWed               = 'Wed';
rsShortThu               = 'Thu';
rsShortFri               = 'Fri';
rsShortSat               = 'Sat';
rsShortSun               = 'Sun';
rsLongMon                = 'Monday';
rsLongTue                = 'Tuesday';
rsLongWed                = 'Wednesday';
rsLongThu                = 'Thursday';
rsLongFri                = 'Friday';
rsLongSat                = 'Saturday';
rsLongSun                = 'Sunday';



