{%mainunit gfx_constants.pas}

rsLanguage               = 'Русский';


// Buttons
rsOK                     = 'OK';
rsCancel                 = 'Отмена';
rsHelp                   = 'Справка';
rsOpen                   = 'Открыть';
rsSave                   = 'Сохранить';
rsCreate                 = 'Создать';
rsChange                 = 'Изменить';
rsFind                   = 'Найти';
rsSearch                 = 'Поиск';
rsReplace                = 'Заменить';
rsConfirm                = 'Подтвердить';
rsAll                    = 'Все';
rsSelect                 = 'Выбрать';
rsYes                    = 'Да';
rsNo                     = 'Нет';
rsAbort                  = 'Прервать';
rsRetry                  = 'Повторить';
rsIgnore                 = 'Пропустить';
rsClose                  = 'Закрыть';
rsInsert                 = 'Вставить';
rsEdit                   = 'Редактировать';
rsDelete                 = 'Удалить';
rsExit                   = 'Выход';
rsYesToAll               = 'Да для всех';
rsNoToAll                = 'Нет для всех';


// Captions
rsError                  = 'Ошибка';
rsCriticalError          = 'Критическая ошибка';
rsInformation            = 'Информация';
rsConfirmation           = 'Подтверждение';
rsWarning                = 'Внимание';
rsMessage                = 'Сообщение';


// Standard file filters
rsAllFiles               = 'Все файлы';


// CreateDir Dialog
rsCreateDirectory        = 'Создать директорию';
rsEnterNewDirectory      = 'Укажите имя новой директории';
rsCannotCreateDir        = 'Невозможно создать директорию';


// Font Dialog
rsSelectAFont            = 'Выбор шрифта';
rsName                   = 'Название';
rsCollection             = 'Группа';
rsSize                   = 'Размер';
rsStyle                  = 'Стиль';
rsItalic                 = 'Курсив';
rsBold                   = 'Жирный';
rsUnderScore             = 'Подчеркнутый';
rsExampleText            = 'Пример текста';


// Open Dialog
rsOpenAFile              = 'Открыть файл';
rsFileName               = 'Имя файла';
rsFileType               = 'Тип файла';
rsDrive                  = 'Диск';
rsFiles                  = 'Файлы';
rsDirectories            = 'Директории';
rsShowHidden             = 'Показывать скрытые файлы';


// Save Dialog
rsSaveAFile              = 'Сохранить файл как';


