{%mainunit gfx_constants.pas}

rsLanguage               = 'Deutsch';


// Buttons
rsOK                     = 'OK';
rsCancel                 = 'Abbruch';
rsHelp                   = 'Hilfe';
rsOpen                   = 'ffnen';
rsSave                   = 'Speichern';
rsCreate                 = 'Erzeugen';
rsChange                 = 'Wechseln';
rsFind                   = 'Finden';
rsSearch                 = 'Suchen';
rsReplace                = 'Ersetzen';
rsConfirm                = 'Besttigungs';
rsAll                    = 'Alle';
rsSelect                 = 'Auswahl';
rsYes                    = 'Ja';
rsNo                     = 'Nein';
rsAbort                  = 'bergehen';
rsRetry                  = 'Wiederholen';
rsIgnore                 = 'Ignorieren';
rsClose                  = 'Schlieáen';
rsInsert                 = 'Einfgen';
rsEdit                   = 'Bearbeiten';
rsDelete                 = 'Lschen';
rsExit                   = 'Exit';


// Captions
rsError                  = 'Fehler';
rsCriticalError          = 'Schwerer Fehler';
rsInformation            = 'Information';
rsConfirmation           = 'Besttigen';
rsWarning                = 'Warnung';
rsMessage                = 'Nachricht';


// Standard file filters
rsAllFiles               = 'Alle Dateien';


// CreateDir Dialog
rsCreateDirectory        = 'Verzeichnis erstellen';
rsEnterNewDirectory      = 'Neuenr Verzeichnisname';
rsCannotCreateDir        = 'Verzeichnis kann nicht erzeugt werden';


// Font Dialog
rsSelectAFont            = 'Zeichensatz auswhlen';
rsName                   = 'Name';
rsCollection             = 'Collection';
rsSize                   = 'Gráe';
rsStyle                  = 'Stil';
rsItalic                 = 'Kursiv';
rsBold                   = 'Fett';
rsUnderScore             = 'Unterstrichen';
rsExampleText            = 'Beispieltext';


// Open Dialog
rsOpenAFile              = 'Datei ffnen';
rsFileName               = 'Dateiname';
rsFileType               = 'Dateityp';
rsDrive                  = 'Laufwerk';
rsFiles                  = 'Dateien';
rsDirectories            = 'Verzeichnisse';
rsShowHidden             = 'Show hidden files';


// Save Dialog
rsSaveAFile              = 'Datei speichern';


