{%mainunit gfx_constants.pas}

rsLanguage               = 'Русский';


// Buttons
rsOK                     = 'OK';
rsCancel                 = 'Отмена';
rsHelp                   = 'Справка';
rsOpen                   = 'Открыть';
rsSave                   = 'Сохранить';
rsCreate                 = 'Создать';
rsChange                 = 'Изменить';
rsFind                   = 'Найти';
rsSearch                 = 'Поиск';
rsReplace                = 'Заменить';
rsConfirm                = 'Подтвердить';
rsAll                    = 'Все';
rsSelect                 = 'Выбрать';
rsYes                    = 'Да';
rsNo                     = 'Нет';
rsAbort                  = 'Прервать';
rsRetry                  = 'Повторить';
rsIgnore                 = 'Пропустить';
rsClose                  = 'Закрыть';
rsInsert                 = 'Вставка';
rsEdit                   = 'Редактировать';
rsDelete                 = 'Удалить';
rsExit                   = 'Выход';
rsYesToAll               = 'Да для всех';
rsNoToAll                = 'Нет для всех';
rsCut                    = 'Вырезать';
rsCopy                   = 'Копировать';
rsPaste                  = 'Вставить';


// Captions
rsError                  = 'Ошибка';
rsCriticalError          = 'Критическая ошибка';
rsInformation            = 'Информация';
rsConfirmation           = 'Подтверждение';
rsWarning                = 'Внимание';
rsMessage                = 'Сообщение';
rsAbout                  = 'Информация о %s';


// Standard file filters
rsAllFiles               = 'Все файлы';


// CreateDir Dialog
rsCreateDirectory        = 'Создать директорию';
rsEnterNewDirectory      = 'Укажите имя новой директории';
rsCannotCreateDir        = 'Невозможно создать директорию';


// Font Dialog
rsSelectAFont            = 'Выбор шрифта';
rsName                   = 'Название';
rsCollection             = 'Группа';
rsSize                   = 'Размер';
rsStyle                  = 'Стиль';
rsItalic                 = 'Курсив';
rsBold                   = 'Жирный';
rsUnderScore             = 'Подчеркнутый';
rsTypeface               = 'Начертание';
rsAntiAliasing           = 'Сглаживание';
rsExampleText            = 'Пример текста';
rsCollectionAllFonts     = 'Все шрифты';
rsCollectionRecentlyUsed = 'Ранее использованные';
rsCollectionFavourites   = 'Избранные';
rsCollectionFixedWidth   = 'Моноширинные';
rsCollectionSans         = 'Sans';
rsCollectionSerif        = 'Serif';
rsCollectionFontAliases  = 'Псевдонимы шрифтов';


// Open Dialog
rsOpenAFile              = 'Открыть файл';
rsFileName               = 'Имя файла';
rsFileType               = 'Тип файла';
rsDrive                  = 'Диск';
rsFiles                  = 'Файлы';
rsDirectories            = 'Директории';
rsShowHidden             = 'Показывать скрытые файлы';
rsFileSelection          = 'Выбор файла';
rsFileModifiedTime       = 'Изменен';
rsFileAttributes         = 'Атрибуты';
rsFileRights             = 'Права';
rsFileOwner              = 'Владелец';
rsFileGroup              = 'Группа';


// Save Dialog
rsSaveAFile              = 'Сохранить файл как';


// User Dialog
rsUserName               = 'Имя пользователя';
rsPassword               = 'Пароль';
rsDatabase               = 'База данных';


// Error messages
rsErrListMustBeEmpty     = 'Список должен быть пустым';
rsErrCouldNotOpenDir     = 'Невозможно открыть директорию <%s>';
rsErrItemOfWrongType     = 'Элемент не принадлежит типу <%s>!';
rsErrFailedToCreateDir   = 'Невозможно создать директорию <%s>';
rsErrNotAssigned         = 'Значение <%s> не определено';


// Calendar Combo & Dialog
rsShortMon               = 'Пн';
rsShortTue               = 'Вт';
rsShortWed               = 'Ср';
rsShortThu               = 'Чт';
rsShortFri               = 'Пт';
rsShortSat               = 'Сб';
rsShortSun               = 'Вс';
rsLongMon                = 'Понедельник';
rsLongTue                = 'Вторник';
rsLongWed                = 'Среда';
rsLongThu                = 'Четверг';
rsLongFri                = 'Пятница';
rsLongSat                = 'Суббота';
rsLongSun                = 'Воскресенье';
rsToday                  = 'Сегодня';
rsShortJan               = 'Янв';
rsShortFeb               = 'Фев';
rsShortMar               = 'Мар';
rsShortApr               = 'Апр';
rsShortMay               = 'Май';
rsShortJun               = 'Июн';
rsShortJul               = 'Июл';
rsShortAug               = 'Авг';
rsShortSep               = 'Сен';
rsShortOct               = 'Окт';
rsShortNov               = 'Ноя';
rsShortDec               = 'Дек';
rsLongJan                = 'Январь';
rsLongFeb                = 'Февраль';
rsLongMar                = 'Март';
rsLongApr                = 'Апрель';
rsLongMay                = 'Май';
rsLongJun                = 'Июнь';
rsLongJul                = 'Июль';
rsLongAug                = 'Август';
rsLongSep                = 'Сентябрь';
rsLongOct                = 'Октябрь';
rsLongNov                = 'Ноябрь';
rsLongDec                = 'Декабрь';




// General messages
rsNewItemDetected       = 'A new item has been detected.';
rsAddNewItem            = 'Would you like to add the new item <%s> to the list?';

