{%mainunit gfx_constants.pas}

rsLanguage               = 'English';


// Buttons
rsOK                     = 'OK';
rsCancel                 = 'Cancel';
rsHelp                   = 'Help';
rsOpen                   = 'Open';
rsSave                   = 'Save';
rsCreate                 = 'Create';
rsChange                 = 'Change';
rsFind                   = 'Find';
rsSearch                 = 'Search';
rsReplace                = 'Replace';
rsConfirm                = 'Confirm';
rsAll                    = 'All';
rsSelect                 = 'Select';
rsYes                    = 'Yes';
rsNo                     = 'No';
rsAbort                  = 'Abort';
rsRetry                  = 'Retry';
rsIgnore                 = 'Ignore';
rsClose                  = 'Close';
rsInsert                 = 'Insert';
rsEdit                   = 'Edit';
rsDelete                 = 'Delete';
rsExit                   = 'Exit';
rsYesToAll               = 'Yes to All';
rsNoToAll                = 'No to All';


// Captions
rsError                  = 'Error';
rsCriticalError          = 'Critical Error';
rsInformation            = 'Information';
rsConfirmation           = 'Confirm';
rsWarning                = 'Warning';
rsMessage                = 'Message';


// Standard file filters
rsAllFiles               = 'All Files';


// CreateDir Dialog
rsCreateDirectory        = 'Create directory';
rsEnterNewDirectory      = 'Enter new directory name';
rsCannotCreateDir        = 'Cannot create directory';


// Font Dialog
rsSelectAFont            = 'Select a font';
rsName                   = 'Name';
rsCollection             = 'Collection';
rsSize                   = 'Size';
rsStyle                  = 'Style';
rsItalic                 = 'Italic';
rsBold                   = 'Bold';
rsUnderScore             = 'UnderScore';
rsExampleText            = 'Example Text';


// Open Dialog
rsOpenAFile              = 'Open a file';
rsFileName               = 'Filename';
rsFileType               = 'Type of file';
rsDrive                  = 'Drive';
rsFiles                  = 'Files';
rsDirectories            = 'Directories';
rsShowHidden             = 'Show hidden files';


// Save Dialog
rsSaveAFile              = 'Save file as';


