{%mainunit gfx_constants.pas}

rsLanguage               = 'Русский';


// Buttons
rsOK                     = 'OK';
rsCancel                 = 'Отмена';
rsHelp                   = 'Справка';
rsOpen                   = 'Открыть';
rsSave                   = 'Сохранить';
rsCreate                 = 'Создать';
rsChange                 = 'Изменить';
rsFind                   = 'Найти';
rsSearch                 = 'Поиск';
rsReplace                = 'Заменить';
rsConfirm                = 'Подтвердить';
rsAll                    = 'Все';
rsSelect                 = 'Выбрать';
rsYes                    = 'Да';
rsNo                     = 'Нет';
rsAbort                  = 'Прервать';
rsRetry                  = 'Повторить';
rsIgnore                 = 'Пропустить';
rsClose                  = 'Закрыть';
rsInsert                 = 'Вставить';
rsEdit                   = 'Редактировать';
rsDelete                 = 'Удалить';
rsExit                   = 'Выход';
rsYesToAll               = 'Да для всех';
rsNoToAll                = 'Нет для всех';
rsCut                    = 'Cut';
rsCopy                   = 'Copy';
rsPaste                  = 'Paste';


// Captions
rsError                  = 'Ошибка';
rsCriticalError          = 'Критическая ошибка';
rsInformation            = 'Информация';
rsConfirmation           = 'Подтверждение';
rsWarning                = 'Внимание';
rsMessage                = 'Сообщение';
rsAbout                  = 'About %s';


// Standard file filters
rsAllFiles               = 'Все файлы';


// CreateDir Dialog
rsCreateDirectory        = 'Создать директорию';
rsEnterNewDirectory      = 'Укажите имя новой директории';
rsCannotCreateDir        = 'Невозможно создать директорию';


// Font Dialog
rsSelectAFont            = 'Выбор шрифта';
rsName                   = 'Название';
rsCollection             = 'Группа';
rsSize                   = 'Размер';
rsStyle                  = 'Стиль';
rsItalic                 = 'Курсив';
rsBold                   = 'Жирный';
rsUnderScore             = 'Подчеркнутый';
rsTypeface               = 'Typeface';
rsAntiAliasing           = 'Anti aliasing';
rsExampleText            = 'Пример текста';
rsCollectionAllFonts     = 'All Fonts';
rsCollectionRecentlyUsed = 'Recently Used';
rsCollectionFavourites   = 'Favourites';
rsCollectionFixedWidth   = 'Fixed Width';
rsCollectionSans         = 'Sans';
rsCollectionSerif        = 'Serif';
rsCollectionFontAliases  = 'Font Aliases';


// Open Dialog
rsOpenAFile              = 'Открыть файл';
rsFileName               = 'Имя файла';
rsFileType               = 'Тип файла';
rsDrive                  = 'Диск';
rsFiles                  = 'Файлы';
rsDirectories            = 'Директории';
rsShowHidden             = 'Показывать скрытые файлы';
rsFileSelection          = 'File Selection';
rsFileModifiedTime       = 'Mod. Time';
rsFileAttributes         = 'Attributes';
rsFileRights             = 'Rights';
rsFileOwner              = 'Owner';
rsFileGroup              = 'Group';


// Save Dialog
rsSaveAFile              = 'Сохранить файл как';


// Error messages
rsErrListMustBeEmpty     = 'Список должен быть пустым';
rsErrCouldNotOpenDir     = 'Could not open the directory <%s>';
rsErrItemOfWrongType     = 'Item is not of <%s> type!';
rsErrFailedToCreateDir   = 'Failed to create the directory <%s>';
rsErrNotAssigned         = '<%s> not assigned';


// Calendar Combo & Dialog
rsShortMon               = 'Mon';
rsShortTue               = 'Tue';
rsShortWed               = 'Wed';
rsShortThu               = 'Thu';
rsShortFri               = 'Fri';
rsShortSat               = 'Sat';
rsShortSun               = 'Sun';
rsLongMon                = 'Monday';
rsLongTue                = 'Tuesday';
rsLongWed                = 'Wednesday';
rsLongThu                = 'Thursday';
rsLongFri                = 'Friday';
rsLongSat                = 'Saturday';
rsLongSun                = 'Sunday';



