{%mainunit gfx_constants.pas}

rsLanguage               = 'Français';


// Buttons
rsOK                     = 'OK';
rsCancel                 = 'Annuler';
rsHelp                   = 'Aide';
rsOpen                   = 'Ouvrir';
rsSave                   = 'Sauver';
rsCreate                 = 'Créer';
rsChange                 = 'Changements';
rsFind                   = 'Trouver';
rsSearch                 = 'Chercher';
rsReplace                = 'Remplacer';
rsConfirm                = 'Confirmer';
rsAll                    = 'Tous';
rsSelect                 = 'Selectionner';
rsYes                    = 'Oui';
rsNo                     = 'Non';
rsAbort                  = 'Arrêter';
rsRetry                  = 'Retenter';
rsIgnore                 = 'Ignorer';
rsClose                  = 'Fermer';
rsInsert                 = 'Insérer';
rsEdit                   = 'Editer';
rsDelete                 = 'Supprimer';
rsExit                   = 'Sortir';
rsYesToAll               = 'Oui à tous';
rsNoToAll                = 'Non à tous';
rsCut                    = 'Cut';
rsCopy                   = 'Copy';
rsPaste                  = 'Paste';


// Captions
rsError                  = 'Erreur';
rsCriticalError          = 'Erreur critique';
rsInformation            = 'Information';
rsConfirmation           = 'Confirmation';
rsWarning                = 'Alerte';
rsMessage                = 'Message';
rsAbout                  = 'About %s';


// Standard file filters
rsAllFiles               = 'Tous les fichiers';


// CreateDir Dialog
rsCreateDirectory        = 'Créer répertoire';
rsEnterNewDirectory      = 'Entrer nom du nouveau répertoire';
rsCannotCreateDir        = 'Impossible de créer le répertoire';


// Font Dialog
rsSelectAFont            = 'Choisir la police';
rsName                   = 'Nom';
rsCollection             = 'Collection';
rsSize                   = 'Taille';
rsStyle                  = 'Style';
rsItalic                 = 'Italique';
rsBold                   = 'Gras';
rsUnderScore             = 'Souligné';
rsTypeface               = 'Typeface';
rsAntiAliasing           = 'Anti aliasing';
rsExampleText            = 'Texte exemple';
rsCollectionAllFonts     = 'All Fonts';
rsCollectionRecentlyUsed = 'Recently Used';
rsCollectionFavourites   = 'Favourites';
rsCollectionFixedWidth   = 'Fixed Width';
rsCollectionSans         = 'Sans';
rsCollectionSerif        = 'Serif';
rsCollectionFontAliases  = 'Font Aliases';


// Open Dialog
rsOpenAFile              = 'Ouvrir un fichier';
rsFileName               = 'Nom de fichier';
rsFileType               = 'Type de fichier';
rsDrive                  = 'Disque';
rsFiles                  = 'Fichiers';
rsDirectories            = 'Répertoires';
rsShowHidden             = 'Montrer les fichiers cachés';
rsFileSelection          = 'File Selection';
rsFileModifiedTime       = 'Mod. Time';
rsFileAttributes         = 'Attributes';
rsFileRights             = 'Rights';
rsFileOwner              = 'Owner';
rsFileGroup              = 'Group';


// Save Dialog
rsSaveAFile              = 'Sauver sous';


// Error messages
rsErrListMustBeEmpty     = 'Liste doit être vide';
rsErrCouldNotOpenDir     = 'Could not open the directory <%s>';
rsErrItemOfWrongType     = 'Item is not of <%s> type!';
rsErrFailedToCreateDir   = 'Failed to create the directory <%s>';
rsErrNotAssigned         = '<%s> not assigned';


// Calendar Combo & Dialog
rsShortMon               = 'Mon';
rsShortTue               = 'Tue';
rsShortWed               = 'Wed';
rsShortThu               = 'Thu';
rsShortFri               = 'Fri';
rsShortSat               = 'Sat';
rsShortSun               = 'Sun';
rsLongMon                = 'Monday';
rsLongTue                = 'Tuesday';
rsLongWed                = 'Wednesday';
rsLongThu                = 'Thursday';
rsLongFri                = 'Friday';
rsLongSat                = 'Saturday';
rsLongSun                = 'Sunday';



