{%mainunit gfx_constants.pas}

rsLanguage               = 'Français';


// Buttons
rsOK                     = 'OK';
rsCancel                 = 'Annuler';
rsHelp                   = 'Aide';
rsOpen                   = 'Ouvrir';
rsSave                   = 'Sauver';
rsCreate                 = 'Créer';
rsChange                 = 'Changements';
rsFind                   = 'Trouver';
rsSearch                 = 'Chercher';
rsReplace                = 'Remplacer';
rsConfirm                = 'Confirmer';
rsAll                    = 'Tous';
rsSelect                 = 'Selectionner';
rsYes                    = 'Oui';
rsNo                     = 'Non';
rsAbort                  = 'Arrêter';
rsRetry                  = 'Retenter';
rsIgnore                 = 'Ignorer';
rsClose                  = 'Fermer';
rsInsert                 = 'Insérer';
rsEdit                   = 'Editer';
rsDelete                 = 'Supprimer';
rsExit                   = 'Sortir';
rsYesToAll               = 'Oui à tous';
rsNoToAll                = 'Non à tous';
rsCut                    = 'Couper';
rsCopy                   = 'Copier';
rsPaste                  = 'Coller';


// Captions
rsError                  = 'Erreur';
rsCriticalError          = 'Erreur critique';
rsInformation            = 'Information';
rsConfirmation           = 'Confirmation';
rsWarning                = 'Alerte';
rsMessage                = 'Message';
rsAbout                  = 'A propos de %s';


// Standard file filters
rsAllFiles               = 'Tous les fichiers';


// CreateDir Dialog
rsCreateDirectory        = 'Créer répertoire';
rsEnterNewDirectory      = 'Entrer nom du nouveau répertoire';
rsCannotCreateDir        = 'Impossible de créer le répertoire';


// Font Dialog
rsSelectAFont            = 'Choisir la police';
rsName                   = 'Nom';
rsCollection             = 'Collection';
rsSize                   = 'Taille';
rsStyle                  = 'Style';
rsItalic                 = 'Italique';
rsBold                   = 'Gras';
rsUnderScore             = 'Souligné';
rsTypeface               = 'Style';
rsAntiAliasing           = 'Anti alias';
rsExampleText            = 'Texte exemple';
rsCollectionAllFonts     = 'Toutes les polices';
rsCollectionRecentlyUsed = 'Récemment utilisées';
rsCollectionFavourites   = 'Favorites';
rsCollectionFixedWidth   = 'Largeur fixe';
rsCollectionSans         = 'Sans';
rsCollectionSerif        = 'Serif';
rsCollectionFontAliases  = 'Alias';


// Open Dialog
rsOpenAFile              = 'Ouvrir un fichier';
rsFileName               = 'Nom de fichier';
rsFileType               = 'Type de fichier';
rsDrive                  = 'Disque';
rsFiles                  = 'Fichiers';
rsDirectories            = 'Répertoires';
rsShowHidden             = 'Montrer les fichiers cachés';
rsFileSelection          = 'Sélection fichier';
rsFileModifiedTime       = 'Date modif.';
rsFileAttributes         = 'Attributs';
rsFileRights             = 'Droits';
rsFileOwner              = 'Propriétaire';
rsFileGroup              = 'Groupe';


// Save Dialog
rsSaveAFile              = 'Sauver sous';


// User Dialog
rsUserName               = 'User name';
rsPassword               = 'Password';
rsDatabase               = 'Database';


// Error messages
rsErrListMustBeEmpty     = 'Liste doit être vide';
rsErrCouldNotOpenDir     = 'Le répertoire <%s> n''a pas pu être ouvert';
rsErrItemOfWrongType     = 'L''item n''est pas du type <%s>!';
rsErrFailedToCreateDir   = 'Le répertoire <%s> n''a pas pu être ouvert';
rsErrNotAssigned         = '<%s> n''est pas assigné';


// Calendar Combo & Dialog
rsShortMon               = 'Lun';
rsShortTue               = 'Mar';
rsShortWed               = 'Mer';
rsShortThu               = 'Jeu';
rsShortFri               = 'Ven';
rsShortSat               = 'Sam';
rsShortSun               = 'Dim';
rsLongMon                = 'Lundi';
rsLongTue                = 'Mardi';
rsLongWed                = 'Mercredi';
rsLongThu                = 'Jeudi';
rsLongFri                = 'Vendredi';
rsLongSat                = 'Samedi';
rsLongSun                = 'Dimanche';



