{%mainunit gfx_constants.pas}

rsLanguage               = 'Français';


// Buttons
rsOK                     = 'OK';
rsCancel                 = 'Annuler';
rsHelp                   = 'Aide';
rsOpen                   = 'Ouvrir';
rsSave                   = 'Sauver';
rsCreate                 = 'Créer';
rsChange                 = 'Changements';
rsFind                   = 'Trouver';
rsSearch                 = 'Chercher';
rsReplace                = 'Remplacer';
rsConfirm                = 'Confirmer';
rsAll                    = 'Tous';
rsSelect                 = 'Selectionner';
rsYes                    = 'Oui';
rsNo                     = 'Non';
rsAbort                  = 'Arrêter';
rsRetry                  = 'Retenter';
rsIgnore                 = 'Ignorer';
rsClose                  = 'Fermer';
rsInsert                 = 'Insérer';
rsEdit                   = 'Editer';
rsDelete                 = 'Supprimer';
rsExit                   = 'Sortir';
rsYesToAll               = 'Oui à tous';
rsNoToAll                = 'Non à tous';


// Captions
rsError                  = 'Erreur';
rsCriticalError          = 'Erreur critique';
rsInformation            = 'Information';
rsConfirmation           = 'Confirmation';
rsWarning                = 'Alerte';
rsMessage                = 'Message';


// Standard file filters
rsAllFiles               = 'Tous les fichiers';


// CreateDir Dialog
rsCreateDirectory        = 'Créer répertoire';
rsEnterNewDirectory      = 'Entrer nom du nouveau répertoire';
rsCannotCreateDir        = 'Impossible de créer le répertoire';


// Font Dialog
rsSelectAFont            = 'Choisir la police';
rsName                   = 'Nom';
rsCollection             = 'Collection';
rsSize                   = 'Taille';
rsStyle                  = 'Style';
rsItalic                 = 'Italique';
rsBold                   = 'Gras';
rsUnderScore             = 'Souligné';
rsExampleText            = 'Texte exemple';


// Open Dialog
rsOpenAFile              = 'Ouvrir un fichier';
rsFileName               = 'Nom de fichier';
rsFileType               = 'Type de fichier';
rsDrive                  = 'Disque';
rsFiles                  = 'Fichiers';
rsDirectories            = 'Répertoires';
rsShowHidden             = 'Montrer les fichiers cachés';


// Save Dialog
rsSaveAFile              = 'Sauver sous';


// Error messages
rsListMustBeEmpty        = 'Liste doit être vide';

