{%mainunit gfx_constants.pas}

rsLanguage               = 'Español';


// Buttons
rsOK                     = 'Aceptar';
rsCancel                 = 'Cancelar';
rsHelp                   = 'Ayuda';
rsOpen                   = 'Abrir';
rsSave                   = 'Guardar';
rsCreate                 = 'Crear';
rsChange                 = 'Cambiar';
rsFind                   = 'Buscar';
rsSearch                 = 'Buscar';
rsReplace                = 'Reemplazar';
rsConfirm                = 'Confirmar';
rsAll                    = 'Todos';
rsSelect                 = 'Seleccionar';
rsYes                    = 'Si';
rsNo                     = 'No';
rsAbort                  = 'Abortar';
rsRetry                  = 'Reintentar';
rsIgnore                 = 'Ignorar';
rsClose                  = 'Cerrar';
rsInsert                 = 'Insertar';
rsEdit                   = 'Editar';
rsDelete                 = 'Borrar';
rsExit                   = 'Salir';
rsYesToAll               = 'Si a Todo';
rsNoToAll                = 'No a Todo';


// Captions
rsError                  = 'Error';
rsCriticalError          = 'Error Crítico';
rsInformation            = 'Información';
rsConfirmation           = 'Confirmación';
rsWarning                = 'Advertencia';
rsMessage                = 'Mensaje';


// Standard file filters
rsAllFiles               = 'Todos los Archivos';


// CreateDir Dialog
rsCreateDirectory        = 'Crear carpeta';
rsEnterNewDirectory      = 'Ingrese el nombre de la carpeta nueva';
rsCannotCreateDir        = 'No se puede crear la carpeta';


// Font Dialog
rsSelectAFont            = 'Seleccione una fuente';
rsName                   = 'Nombre';
rsCollection             = 'Colección';
rsSize                   = 'Tamaño';
rsStyle                  = 'Estilo';
rsItalic                 = 'Italica';
rsBold                   = 'Negrita';
rsUnderScore             = 'Subrayado';
rsExampleText            = 'Texto de Ejemplo';


// Open Dialog
rsOpenAFile              = 'Abrir un archivo';
rsFileName               = 'Nombre de archivo';
rsFileType               = 'Tipo de archivo';
rsDrive                  = 'Unidad';
rsFiles                  = 'Archivos';
rsDirectories            = 'Carpetas';
rsShowHidden             = 'Mostrar archivos ocultos';


// Save Dialog
rsSaveAFile              = 'Guardar como';

// Error messages
rsListMustBeEmpty        = 'La lista debe estar vacia';



