{%mainunit gfx_constants.pas}

rsLanguage               = 'Deutsch';


// Buttons
rsOK                     = 'OK';
rsCancel                 = 'Abbruch';
rsHelp                   = 'Hilfe';
rsOpen                   = 'ffnen';
rsSave                   = 'Speichern';
rsCreate                 = 'Erzeugen';
rsChange                 = 'Wechseln';
rsFind                   = 'Finden';
rsSearch                 = 'Suchen';
rsReplace                = 'Ersetzen';
rsConfirm                = 'Besttigungs';
rsAll                    = 'Alle';
rsSelect                 = 'Auswahl';
rsYes                    = 'Ja';
rsNo                     = 'Nein';
rsAbort                  = 'bergehen';
rsRetry                  = 'Wiederholen';
rsIgnore                 = 'Ignorieren';
rsClose                  = 'Schlieáen';
rsInsert                 = 'Einfgen';
rsEdit                   = 'Bearbeiten';
rsDelete                 = 'Lschen';
rsExit                   = 'Exit';
rsYesToAll               = 'Yes to All';
rsNoToAll                = 'No to All';
rsCut                    = 'Cut';
rsCopy                   = 'Copy';
rsPaste                  = 'Paste';


// Captions
rsError                  = 'Fehler';
rsCriticalError          = 'Schwerer Fehler';
rsInformation            = 'Information';
rsConfirmation           = 'Bestätigen';
rsWarning                = 'Warnung';
rsMessage                = 'Nachricht';
rsAbout                  = 'About %s';


// Standard file filters
rsAllFiles               = 'Alle Dateien';


// CreateDir Dialog
rsCreateDirectory        = 'Verzeichnis erstellen';
rsEnterNewDirectory      = 'Neuenr Verzeichnisname';
rsCannotCreateDir        = 'Verzeichnis kann nicht erzeugt werden';


// Font Dialog
rsSelectAFont            = 'Wählen Sie eine Schriftart';
rsName                   = 'Name';
rsCollection             = 'Collection';
rsSize                   = 'Größe';
rsStyle                  = 'Stil';
rsItalic                 = 'Kursiv';
rsBold                   = 'Fett';
rsUnderScore             = 'Unterstrichen';
rsTypeface               = 'Typeface';
rsAntiAliasing           = 'Anti aliasing';
rsExampleText            = 'Beispieltext';
rsCollectionAllFonts     = 'All Fonts';
rsCollectionRecentlyUsed = 'Recently Used';
rsCollectionFavourites   = 'Favourites';
rsCollectionFixedWidth   = 'Fixed Width';
rsCollectionSans         = 'Sans';
rsCollectionSerif        = 'Serif';
rsCollectionFontAliases  = 'Font Aliases';


// Open Dialog
rsOpenAFile              = 'Öffnen einer Datei';
rsFileName               = 'Dateiname';
rsFileType               = 'Dateityp';
rsDrive                  = 'Laufwerk';
rsFiles                  = 'Dateien';
rsDirectories            = 'Verzeichnisse';
rsShowHidden             = 'Show hidden files';
rsFileSelection          = 'File Selection';
rsFileModifiedTime       = 'Mod. Time';
rsFileAttributes         = 'Attributes';
rsFileRights             = 'Rights';
rsFileOwner              = 'Owner';
rsFileGroup              = 'Group';


// Save Dialog
rsSaveAFile              = 'Datei speichern';


// User Dialog
rsUserName               = 'User name';
rsPassword               = 'Password';


// Error messages
rsErrListMustBeEmpty     = 'Liste müssen leer sein';
rsErrCouldNotOpenDir     = 'Could not open the directory <%s>';
rsErrItemOfWrongType     = 'Item is not of <%s> type!';
rsErrFailedToCreateDir   = 'Failed to create the directory <%s>';
rsErrNotAssigned         = '<%s> not assigned';


// Calendar Combo & Dialog
rsShortMon               = 'Mon';
rsShortTue               = 'Tue';
rsShortWed               = 'Wed';
rsShortThu               = 'Thu';
rsShortFri               = 'Fri';
rsShortSat               = 'Sat';
rsShortSun               = 'Sun';
rsLongMon                = 'Monday';
rsLongTue                = 'Tuesday';
rsLongWed                = 'Wednesday';
rsLongThu                = 'Thursday';
rsLongFri                = 'Friday';
rsLongSat                = 'Saturday';
rsLongSun                = 'Sunday';



