{%mainunit gfx_constants.pas}

rsLanguage               = 'Afrikaans';


// Buttons
rsOK                     = 'Goed';
rsCancel                 = 'Kanselleer';
rsHelp                   = 'Hulp';
rsOpen                   = 'Maak oop';
rsSave                   = 'Stoor';
rsCreate                 = 'Create';
rsChange                 = 'Verander';
rsFind                   = 'Vind';
rsSearch                 = 'Soek';
rsReplace                = 'Vervang';
rsConfirm                = 'Confirm';
rsAll                    = 'Alles';
rsSelect                 = 'Select';
rsYes                    = 'Ja';
rsNo                     = 'Nee';
rsAbort                  = 'Abort';
rsRetry                  = 'Probeer weer';
rsIgnore                 = 'Ignoreer';
rsClose                  = 'Sluit';
rsInsert                 = 'Insert';
rsEdit                   = 'Redigeer';
rsDelete                 = 'Delete';
rsExit                   = 'Staak';
rsYesToAll               = 'Ja vir Alles';
rsNoToAll                = 'Nee vir Alles';


// Captions
rsError                  = 'Fout';
rsCriticalError          = 'Kritiese Fout';
rsInformation            = 'Informasie';
rsConfirmation           = 'Confirm';
rsWarning                = 'Waarskuwing';
rsMessage                = 'Boodskap';


// Standard file filters
rsAllFiles               = 'Alle Lêers';


// CreateDir Dialog
rsCreateDirectory        = 'Create directory';
rsEnterNewDirectory      = 'Enter new directory name';
rsCannotCreateDir        = 'Cannot create directory';


// Font Dialog
rsSelectAFont            = 'Select a font';
rsName                   = 'Naam';
rsCollection             = 'Collection';
rsSize                   = 'Groote';
rsStyle                  = 'Steil';
rsItalic                 = 'Italic';
rsBold                   = 'Bold';
rsUnderScore             = 'Onderstreep';
rsExampleText            = 'Example Text';


// Open Dialog
rsOpenAFile              = 'Maak ''n leêr op';
rsFileName               = 'Lêer naam';
rsFileType               = 'Tipe Leêr';
rsDrive                  = 'Drive';
rsFiles                  = 'Lêers';
rsDirectories            = 'Directories';
rsShowHidden             = 'Show hidden files';


// Save Dialog
rsSaveAFile              = 'Stoor ''n lêer';


