{%mainunit gfx_constants.pas}

rsLanguage               = 'Deutsch';


// Buttons
rsOK                     = 'OK';
rsCancel                 = 'Abbrechen';
rsHelp                   = 'Hilfe';
rsOpen                   = 'Öffnen';
rsSave                   = 'Speichern';
rsCreate                 = 'Anlegen';
rsChange                 = 'Ändern';
rsFind                   = 'Finden';
rsSearch                 = 'Suchen';
rsReplace                = 'Ersetzen';
rsConfirm                = 'Bestätigen';
rsAll                    = 'Alle';
rsSelect                 = 'Ausgewählte';
rsYes                    = 'Ja';
rsNo                     = 'Nein';
rsAbort                  = 'Abbrechen';
rsRetry                  = 'Wiederholen';
rsIgnore                 = 'Übergehen';
rsClose                  = 'Schließen';
rsInsert                 = 'Einfügen';
rsEdit                   = 'Bearbeiten';
rsDelete                 = 'Löschen';
rsExit                   = 'Verlassen';
rsYesToAll               = 'Ja zu allem';
rsNoToAll                = 'Nein zu allem';
rsCut                    = 'Ausschneiden';
rsCopy                   = 'Kopieren';
rsPaste                  = 'Einfügen';


// Captions
rsError                  = 'Fehler';
rsCriticalError          = 'Kritischer Fehler';
rsInformation            = 'Information';
rsConfirmation           = 'Bestätigung';
rsWarning                = 'Warnung';
rsMessage                = 'Meldung';
rsAbout                  = 'Über %s';


// Standard file filters
rsAllFiles               = 'Alle Dateien';


// CreateDir Dialog
rsCreateDirectory        = 'Verzeichnis anlegen';
rsEnterNewDirectory      = 'Verzeichnisname eingeben';
rsCannotCreateDir        = 'Kann Verzeichnis nicht anlegen';


// Font Dialog
rsSelectAFont            = 'Schriftart auswählen';
rsName                   = 'Name';
rsCollection             = 'Sammlung';
rsSize                   = 'Größe';
rsStyle                  = 'Stil';
rsItalic                 = 'Kursiv';
rsBold                   = 'Fett';
rsUnderScore             = 'Unterstrichen';
rsTypeface               = 'Schriftart';
rsAntiAliasing           = 'Antialiasing';
rsExampleText            = 'Beispieltext';
rsCollectionAllFonts     = 'Alle Schriften';
rsCollectionRecentlyUsed = 'Zuletzt verwendet';
rsCollectionFavourites   = 'Favoriten';
rsCollectionFixedWidth   = 'Feste Breite';
rsCollectionSans         = 'Serifenlos';
rsCollectionSerif        = 'Serifenbehaftet';
rsCollectionFontAliases  = 'Font-Aliase';


// Open Dialog
rsOpenAFile              = 'Eine Datei öffnen';
rsFileName               = 'Dateiname';
rsFileType               = 'Art der Datei';
rsDrive                  = 'Laufwerk';
rsFiles                  = 'Dateien';
rsDirectories            = 'Verzeichnisse';
rsShowHidden             = 'Zeige versteckte Dateien';
rsFileSelection          = 'Dateiauswahl';
rsFileModifiedTime       = 'Änderungszeit';
rsFileAttributes         = 'Attribute';
rsFileRights             = 'Rechte';
rsFileOwner              = 'Eigentümer';
rsFileGroup              = 'Gruppe';


// Save Dialog
rsSaveAFile              = 'Datei speichern unter';


// User Dialog
rsUserName               = 'Username';
rsPassword               = 'Passwort';
rsDatabase               = 'Datenbank';


// Error messages
rsErrListMustBeEmpty     = 'Liste muß leer sein';
rsErrCouldNotOpenDir     = 'Konnte Verzeichnis <%> nicht anlegen';
rsErrItemOfWrongType     = 'Eintrag ist nicht vom Typ <%s>!';
rsErrFailedToCreateDir   = 'Konnte Verzeichnis <%s> nicht anlegen';
rsErrNotAssigned         = '<%s> nicht zugewiesen';


// Calendar Combo & Dialog
rsShortMon               = 'Mon';
rsShortTue               = 'Die';
rsShortWed               = 'Mit';
rsShortThu               = 'Don';
rsShortFri               = 'Fre';
rsShortSat               = 'Sam';
rsShortSun               = 'Son';
rsLongMon                = 'Montag';
rsLongTue                = 'Dienstag';
rsLongWed                = 'Mittwoch';
rsLongThu                = 'Donnerstag';
rsLongFri                = 'Freitag';
rsLongSat                = 'Samstag';
rsLongSun                = 'Sonntag';
rsToday                  = 'Heute';
rsShortJan               = 'Jan';
rsShortFeb               = 'Feb';
rsShortMar               = 'Mrz';
rsShortApr               = 'Apr';
rsShortMay               = 'Mai';
rsShortJun               = 'Jun';
rsShortJul               = 'Jul';
rsShortAug               = 'Aug';
rsShortSep               = 'Sep';
rsShortOct               = 'Okt';
rsShortNov               = 'Nov';
rsShortDec               = 'Dez';
rsLongJan                = 'Januar';
rsLongFeb                = 'Februar';
rsLongMar                = 'März';
rsLongApr                = 'April';
rsLongMay                = 'Mai';
rsLongJun                = 'Juni';
rsLongJul                = 'Juli';
rsLongAug                = 'August';
rsLongSep                = 'September';
rsLongOct                = 'Oktober';
rsLongNov                = 'November';
rsLongDec                = 'Dezember';




// General messages
rsNewItemDetected       = 'A new item has been detected.';
rsAddNewItem            = 'Would you like to add the new item <%s> to the list?';

