{%mainunit gfx_constants.pas}

rsLanguage               = 'Português';


// Buttons
rsOK                     = 'OK';
rsCancel                 = 'Cancelar';
rsHelp                   = 'Ajuda';
rsOpen                   = 'Abir';
rsSave                   = 'Salvar';
rsCreate                 = 'Criar';
rsChange                 = 'Editar';
rsFind                   = 'Encontrar';
rsSearch                 = 'Pesquisar';
rsReplace                = 'Substituir';
rsConfirm                = 'Confirmar';
rsAll                    = 'Todos';
rsSelect                 = 'Selecionar';
rsYes                    = 'Sim';
rsNo                     = 'Não';
rsAbort                  = 'Abortar';
rsRetry                  = 'Retentar';
rsIgnore                 = 'Ignorar';
rsClose                  = 'Fechar';
rsInsert                 = 'Inserir';
rsEdit                   = 'Editar';
rsDelete                 = 'Deletar';
rsExit                   = 'Sair';
rsYesToAll               = 'Sim para todos';
rsNoToAll                = 'Não para todos';



// Captions
rsError                  = 'Erro';
rsCriticalError          = 'Erro Crítico';
rsInformation            = 'Informação';
rsConfirmation           = 'Confirmação';
rsWarning                = 'Advertência';
rsMessage                = 'Mensagem';


// Standard file filters
rsAllFiles               = 'Todos os arquivos';


// CreateDir Dialog
rsCreateDirectory        = 'Criar diretório';
rsEnterNewDirectory      = 'Digite o nome do novo diretório';
rsCannotCreateDir        = 'Não foi possível criar diretório';


// Font Dialog
rsSelectAFont            = 'Selecione a fonte';
rsName                   = 'Nome';
rsCollection             = 'Coleção';
rsSize                   = 'Tamanho';
rsStyle                  = 'Estilo';
rsItalic                 = 'Itálico';
rsBold                   = 'Negrito';
rsUnderScore             = 'Sublinhado';
rsExampleText            = 'Texto de Exemplo';


// Open Dialog
rsOpenAFile              = 'Abrir um arquivo';
rsFileName               = 'Nome do arquivo';
rsFileType               = 'Tipo de arquivo';
rsDrive                  = 'Drive';
rsFiles                  = 'Arquivos';
rsDirectories            = 'Diretórios';
rsShowHidden             = 'Mostrar arquivos ocultos';


// Save Dialog
rsSaveAFile              = 'Salvar arquivo como';


