{%mainunit gfx_constants.pas}

rsLanguage               = 'English';


// Buttons
rsOK                     = 'OK';
rsCancel                 = 'Cancel';
rsHelp                   = 'Help';
rsOpen                   = 'Open';
rsSave                   = 'Save';
rsCreate                 = 'Create';
rsChange                 = 'Change';
rsFind                   = 'Find';
rsSearch                 = 'Search';
rsReplace                = 'Replace';
rsConfirm                = 'Confirm';
rsAll                    = 'All';
rsSelect                 = 'Select';
rsYes                    = 'Yes';
rsNo                     = 'No';
rsAbort                  = 'Abort';
rsRetry                  = 'Retry';
rsIgnore                 = 'Ignore';
rsClose                  = 'Close';
rsInsert                 = 'Insert';
rsEdit                   = 'Edit';
rsDelete                 = 'Delete';
rsExit                   = 'Exit';
rsYesToAll               = 'Yes to All';
rsNoToAll                = 'No to All';
rsCut                    = 'Cut';
rsCopy                   = 'Copy';
rsPaste                  = 'Paste';


// Captions
rsError                  = 'Error';
rsCriticalError          = 'Critical Error';
rsInformation            = 'Information';
rsConfirmation           = 'Confirmation';
rsWarning                = 'Warning';
rsMessage                = 'Message';
rsAbout                  = 'About %s';


// Standard file filters
rsAllFiles               = 'All Files';


// CreateDir Dialog
rsCreateDirectory        = 'Create directory';
rsEnterNewDirectory      = 'Enter new directory name';
rsCannotCreateDir        = 'Cannot create directory';


// Font Dialog
rsSelectAFont            = 'Select a font';
rsName                   = 'Name';
rsCollection             = 'Collection';
rsSize                   = 'Size';
rsStyle                  = 'Style';
rsItalic                 = 'Italic';
rsBold                   = 'Bold';
rsUnderScore             = 'UnderScore';
rsTypeface               = 'Typeface';
rsAntiAliasing           = 'Anti aliasing';
rsExampleText            = 'Example Text';
rsCollectionAllFonts     = 'All Fonts';
rsCollectionRecentlyUsed = 'Recently Used';
rsCollectionFavourites   = 'Favourites';
rsCollectionFixedWidth   = 'Fixed Width';
rsCollectionSans         = 'Sans';
rsCollectionSerif        = 'Serif';
rsCollectionFontAliases  = 'Font Aliases';


// Open Dialog
rsOpenAFile              = 'Open a file';
rsFileName               = 'Filename';
rsFileType               = 'Type of file';
rsDrive                  = 'Drive';
rsFiles                  = 'Files';
rsDirectories            = 'Directories';
rsShowHidden             = 'Show hidden files';
rsFileSelection          = 'File Selection';
rsFileModifiedTime       = 'Mod. Time';
rsFileAttributes         = 'Attributes';
rsFileRights             = 'Rights';
rsFileOwner              = 'Owner';
rsFileGroup              = 'Group';


// Save Dialog
rsSaveAFile              = 'Save file as';


// User Dialog
rsUserName               = 'User name';
rsPassword               = 'Password';


// Error messages
rsErrListMustBeEmpty     = 'List must be empty';
rsErrCouldNotOpenDir     = 'Could not open the directory <%s>';
rsErrItemOfWrongType     = 'Item is not of <%s> type!';
rsErrFailedToCreateDir   = 'Failed to create the directory <%s>';
rsErrNotAssigned         = '<%s> not assigned';


// Calendar Combo & Dialog
rsShortMon               = 'Mon';
rsShortTue               = 'Tue';
rsShortWed               = 'Wed';
rsShortThu               = 'Thu';
rsShortFri               = 'Fri';
rsShortSat               = 'Sat';
rsShortSun               = 'Sun';
rsLongMon                = 'Monday';
rsLongTue                = 'Tuesday';
rsLongWed                = 'Wednesday';
rsLongThu                = 'Thursday';
rsLongFri                = 'Friday';
rsLongSat                = 'Saturday';
rsLongSun                = 'Sunday';



