{%mainunit gfx_constants.pas}

rsLanguage               = 'Português';


// Buttons
rsOK                     = 'OK';
rsCancel                 = 'Cancelar';
rsHelp                   = 'Ajuda';
rsOpen                   = 'Abir';
rsSave                   = 'Salvar';
rsCreate                 = 'Criar';
rsChange                 = 'Editar';
rsFind                   = 'Encontrar';
rsSearch                 = 'Pesquisar';
rsReplace                = 'Substituir';
rsConfirm                = 'Confirmar';
rsAll                    = 'Todos';
rsSelect                 = 'Selecionar';
rsYes                    = 'Sim';
rsNo                     = 'Não';
rsAbort                  = 'Abortar';
rsRetry                  = 'Retentar';
rsIgnore                 = 'Ignorar';
rsClose                  = 'Fechar';
rsInsert                 = 'Inserir';
rsEdit                   = 'Editar';
rsDelete                 = 'Deletar';
rsExit                   = 'Sair';
rsYesToAll               = 'Sim para todos';
rsNoToAll                = 'Não para todos';
rsCut                    = 'Cut';
rsCopy                   = 'Copy';
rsPaste                  = 'Paste';


// Captions
rsError                  = 'Erro';
rsCriticalError          = 'Erro Crítico';
rsInformation            = 'Informação';
rsConfirmation           = 'Confirmação';
rsWarning                = 'Advertência';
rsMessage                = 'Mensagem';
rsAbout                  = 'About %s';


// Standard file filters
rsAllFiles               = 'Todos os arquivos';


// CreateDir Dialog
rsCreateDirectory        = 'Criar diretório';
rsEnterNewDirectory      = 'Digite o nome do novo diretório';
rsCannotCreateDir        = 'Não foi possível criar diretório';


// Font Dialog
rsSelectAFont            = 'Selecione a fonte';
rsName                   = 'Nome';
rsCollection             = 'Coleção';
rsSize                   = 'Tamanho';
rsStyle                  = 'Estilo';
rsItalic                 = 'Itálico';
rsBold                   = 'Negrito';
rsUnderScore             = 'Sublinhado';
rsTypeface               = 'Typeface';
rsAntiAliasing           = 'Anti aliasing';
rsExampleText            = 'Texto de Exemplo';
rsCollectionAllFonts     = 'All Fonts';
rsCollectionRecentlyUsed = 'Recently Used';
rsCollectionFavourites   = 'Favourites';
rsCollectionFixedWidth   = 'Fixed Width';
rsCollectionSans         = 'Sans';
rsCollectionSerif        = 'Serif';
rsCollectionFontAliases  = 'Font Aliases';


// Open Dialog
rsOpenAFile              = 'Abrir um arquivo';
rsFileName               = 'Nome do arquivo';
rsFileType               = 'Tipo de arquivo';
rsDrive                  = 'Drive';
rsFiles                  = 'Arquivos';
rsDirectories            = 'Diretórios';
rsShowHidden             = 'Mostrar arquivos ocultos';
rsFileSelection          = 'File Selection';
rsFileModifiedTime       = 'Mod. Time';
rsFileAttributes         = 'Attributes';
rsFileRights             = 'Rights';
rsFileOwner              = 'Owner';
rsFileGroup              = 'Group';


// Save Dialog
rsSaveAFile              = 'Salvar arquivo como';


// User Dialog
rsUserName               = 'User name';
rsPassword               = 'Password';
rsDatabase               = 'Database';


// Error messages
rsErrListMustBeEmpty     = 'Lista deve estar vazio';
rsErrCouldNotOpenDir     = 'Could not open the directory <%s>';
rsErrItemOfWrongType     = 'Item is not of <%s> type!';
rsErrFailedToCreateDir   = 'Failed to create the directory <%s>';
rsErrNotAssigned         = '<%s> not assigned';


// Calendar Combo & Dialog
rsShortMon               = 'Mon';
rsShortTue               = 'Tue';
rsShortWed               = 'Wed';
rsShortThu               = 'Thu';
rsShortFri               = 'Fri';
rsShortSat               = 'Sat';
rsShortSun               = 'Sun';
rsLongMon                = 'Monday';
rsLongTue                = 'Tuesday';
rsLongWed                = 'Wednesday';
rsLongThu                = 'Thursday';
rsLongFri                = 'Friday';
rsLongSat                = 'Saturday';
rsLongSun                = 'Sunday';
rsToday                  = 'Today';
rsShortJan               = 'Jan';
rsShortFeb               = 'Feb';
rsShortMar               = 'Mar';
rsShortApr               = 'Apr';
rsShortMay               = 'May';
rsShortJun               = 'Jun';
rsShortJul               = 'Jul';
rsShortAug               = 'Aug';
rsShortSep               = 'Sep';
rsShortOct               = 'Oct';
rsShortNov               = 'Nov';
rsShortDec               = 'Dec';
rsLongJan                = 'January';
rsLongFeb                = 'February';
rsLongMar                = 'March';
rsLongApr                = 'April';
rsLongMay                = 'May';
rsLongJun                = 'June';
rsLongJul                = 'July';
rsLongAug                = 'August';
rsLongSep                = 'September';
rsLongOct                = 'October';
rsLongNov                = 'November';
rsLongDec                = 'December';



