{
    Copyright (c) 2026 Graeme Geldenhuys

    This program is part of the fpGUI Toolkit project.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

    Description:
      Registers the standard fpGUI HVIF icons into fpgIcons.

      Call fpgRegisterStandardIcons once during application initialisation
      (done automatically by TfpgApplication.InternalInit).

      Framework icon ids (used internally by widgets):
        'sys.sb.up'       — scrollbar up arrow
        'sys.sb.down'     — scrollbar down arrow
        'sys.sb.left'     — scrollbar left arrow
        'sys.sb.right'    — scrollbar right arrow / submenu indicator
        'stdimg.check'    — menu checkmark

      Application-level stock icon ids ('stdimg.*' namespace):
        'stdimg.app'                — application-x-executable
        'stdimg.bookmark.new'       — bookmark-new
        'stdimg.caret.bottom'       — caret pointing down
        'stdimg.caret.top'          — caret pointing up
        'stdimg.caret.left'         — caret pointing left
        'stdimg.caret.right'        — caret pointing right
        'stdimg.clear'              — clear/close
        'stdimg.dialog.apply'       — dialog apply
        'stdimg.dialog.error'       — dialog error
        'stdimg.dialog.info'        — dialog information
        'stdimg.dialog.warning'     — dialog warning
        'stdimg.edit.clear'         — edit clear
        'stdimg.edit.copy'          — edit copy
        'stdimg.edit.cut'           — edit cut
        'stdimg.edit.paste'         — edit paste
        'stdimg.edit.redo'          — edit redo
        'stdimg.edit.undo'          — edit undo
        'stdimg.emblem.link'        — symbolic link emblem
        'stdimg.folder'             — folder
        'stdimg.folder.new'         — new folder
        'stdimg.go.down'            — go down
        'stdimg.go.next'            — go next / forward
        'stdimg.go.previous'        — go previous / back
        'stdimg.go.up'              — go up
        'stdimg.hamburger'          — hamburger menu
        'stdimg.help'               — help browser
        'stdimg.list.add'           — list add
        'stdimg.list.remove'        — list remove
        'stdimg.media.floppy'       — save (floppy disk)
        'stdimg.more'               — more options
        'stdimg.preferences'        — preferences / settings
        'stdimg.process.stop'       — stop process
        'stdimg.shutdown'           — system shutdown
        'stdimg.user.home'          — user home
        'stdimg.view.refresh'       — view refresh
        'stdimg.x.addressbook'      — address book
        'stdimg.arrow.downup'       — arrow down-up (sort)
        'stdimg.arrow.updown'       — arrow up-down (sort)
}

unit fpg_stdicons;

{$I fpg_defines.inc}

interface

{ Register the stock HVIF icons into the global fpgIcons store.
  Called automatically by TfpgApplication.InternalInit. }
procedure fpgRegisterStandardIcons;

implementation

uses
  fpg_iconstore;

{ stdhvifimages.inc is generated by svg2hvif --inc. }
{$I stdhvifimages.inc}

procedure fpgRegisterStandardIcons;
begin
  { Framework widget icons — same keys used by scrollbar and menu drawing code }
  fpgIcons.RegisterFromConst('sys.sb.up',    @hvif_std_caret_top,   SizeOf(hvif_std_caret_top));
  fpgIcons.RegisterFromConst('sys.sb.down',  @hvif_std_caret_bottom,SizeOf(hvif_std_caret_bottom));
  fpgIcons.RegisterFromConst('sys.sb.left',  @hvif_std_caret_left,  SizeOf(hvif_std_caret_left));
  fpgIcons.RegisterFromConst('sys.sb.right', @hvif_std_caret_right, SizeOf(hvif_std_caret_right));
  fpgIcons.RegisterFromConst('stdimg.check',  @hvif_std_check,        SizeOf(hvif_std_check));
  fpgIcons.RegisterFromConst('stdimg.ok',     @hvif_std_dialog_apply, SizeOf(hvif_std_dialog_apply));
  fpgIcons.RegisterFromConst('stdimg.cancel', @hvif_std_process_stop, SizeOf(hvif_std_process_stop));

  { Application-level stock icons }
  fpgIcons.RegisterFromConst('stdimg.app',            @hvif_std_application_x_executable, SizeOf(hvif_std_application_x_executable));
  fpgIcons.RegisterFromConst('stdimg.bookmark.new',   @hvif_std_bookmark_new,             SizeOf(hvif_std_bookmark_new));
  fpgIcons.RegisterFromConst('stdimg.caret.bottom',   @hvif_std_caret_bottom,             SizeOf(hvif_std_caret_bottom));
  fpgIcons.RegisterFromConst('stdimg.caret.top',      @hvif_std_caret_top,                SizeOf(hvif_std_caret_top));
  fpgIcons.RegisterFromConst('stdimg.caret.left',     @hvif_std_caret_left,               SizeOf(hvif_std_caret_left));
  fpgIcons.RegisterFromConst('stdimg.caret.right',    @hvif_std_caret_right,              SizeOf(hvif_std_caret_right));
  fpgIcons.RegisterFromConst('stdimg.clear',          @hvif_std_clear,                    SizeOf(hvif_std_clear));
  fpgIcons.RegisterFromConst('stdimg.colpicker',      @hvif_std_color_picker,             SizeOf(hvif_std_color_picker));
  fpgIcons.RegisterFromConst('stdimg.configure',      @hvif_std_configure,                SizeOf(hvif_std_configure));
  fpgIcons.RegisterFromConst('stdimg.dialog.apply',   @hvif_std_dialog_apply,             SizeOf(hvif_std_dialog_apply));
  fpgIcons.RegisterFromConst('stdimg.dialog.error',   @hvif_std_dialog_error,             SizeOf(hvif_std_dialog_error));
  fpgIcons.RegisterFromConst('stdimg.dialog.info',    @hvif_std_dialog_information,       SizeOf(hvif_std_dialog_information));
  fpgIcons.RegisterFromConst('stdimg.dialog.warning', @hvif_std_dialog_warning,           SizeOf(hvif_std_dialog_warning));
  fpgIcons.RegisterFromConst('stdimg.edit.clear',     @hvif_std_edit_clear,               SizeOf(hvif_std_edit_clear));
  fpgIcons.RegisterFromConst('stdimg.edit.copy',      @hvif_std_edit_copy,                SizeOf(hvif_std_edit_copy));
  fpgIcons.RegisterFromConst('stdimg.edit.cut',       @hvif_std_edit_cut,                 SizeOf(hvif_std_edit_cut));
  fpgIcons.RegisterFromConst('stdimg.edit.paste',     @hvif_std_edit_paste,               SizeOf(hvif_std_edit_paste));
  fpgIcons.RegisterFromConst('stdimg.edit.redo',      @hvif_std_edit_redo,                SizeOf(hvif_std_edit_redo));
  fpgIcons.RegisterFromConst('stdimg.edit.undo',      @hvif_std_edit_undo,                SizeOf(hvif_std_edit_undo));
  fpgIcons.RegisterFromConst('stdimg.emblem.link',    @hvif_std_emblem_symbolic_link,     SizeOf(hvif_std_emblem_symbolic_link));
  fpgIcons.RegisterFromConst('stdimg.folder',         @hvif_std_folder,                   SizeOf(hvif_std_folder));
  fpgIcons.RegisterFromConst('stdimg.folder.new',     @hvif_std_folder_new,               SizeOf(hvif_std_folder_new));
  fpgIcons.RegisterFromConst('stdimg.go.down',        @hvif_std_go_down,                  SizeOf(hvif_std_go_down));
  fpgIcons.RegisterFromConst('stdimg.go.next',        @hvif_std_go_next,                  SizeOf(hvif_std_go_next));
  fpgIcons.RegisterFromConst('stdimg.go.previous',    @hvif_std_go_previous,              SizeOf(hvif_std_go_previous));
  fpgIcons.RegisterFromConst('stdimg.go.up',          @hvif_std_go_up,                    SizeOf(hvif_std_go_up));
  fpgIcons.RegisterFromConst('stdimg.hamburger',      @hvif_std_hamburger,                SizeOf(hvif_std_hamburger));
  fpgIcons.RegisterFromConst('stdimg.help',           @hvif_std_help_browser,             SizeOf(hvif_std_help_browser));
  fpgIcons.RegisterFromConst('stdimg.list.add',       @hvif_std_list_add,                 SizeOf(hvif_std_list_add));
  fpgIcons.RegisterFromConst('stdimg.list.remove',    @hvif_std_list_remove,              SizeOf(hvif_std_list_remove));
  fpgIcons.RegisterFromConst('stdimg.media.floppy',   @hvif_std_media_floppy,             SizeOf(hvif_std_media_floppy));
  fpgIcons.RegisterFromConst('stdimg.more',           @hvif_std_more,                     SizeOf(hvif_std_more));
  fpgIcons.RegisterFromConst('stdimg.preferences',    @hvif_std_preferences_system,       SizeOf(hvif_std_preferences_system));
  fpgIcons.RegisterFromConst('stdimg.process.stop',   @hvif_std_process_stop,             SizeOf(hvif_std_process_stop));
  fpgIcons.RegisterFromConst('stdimg.shutdown',       @hvif_std_system_shutdown,           SizeOf(hvif_std_system_shutdown));
  fpgIcons.RegisterFromConst('stdimg.user.home',      @hvif_std_user_home,                SizeOf(hvif_std_user_home));
  fpgIcons.RegisterFromConst('stdimg.view.refresh',   @hvif_std_view_refresh,             SizeOf(hvif_std_view_refresh));
  fpgIcons.RegisterFromConst('stdimg.x.addressbook',  @hvif_std_x_office_address_book,    SizeOf(hvif_std_x_office_address_book));
  fpgIcons.RegisterFromConst('stdimg.arrow.downup',   @hvif_std_arrow_down_up,            SizeOf(hvif_std_arrow_down_up));
  fpgIcons.RegisterFromConst('stdimg.arrow.updown',   @hvif_std_arrow_up_down,            SizeOf(hvif_std_arrow_up_down));
end;

end.
