{
    Copyright (c) 2026 Graeme Geldenhuys

    This program is part of the fpGUI Toolkit project.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

    Description:
      Registers the standard fpGUI HVIF icons into fpgIcons.

      Call fpgRegisterStandardIcons once during application initialisation
      (done automatically by TfpgApplication.InternalInit).

      Stock icon ids use the 'stdicon.' namespace, e.g.:
        'stdicon.dialog.info'
        'stdicon.dialog.warning'
        'stdicon.dialog.error'
        'stdicon.dialog.question'
}

unit fpg_stdicons;

{$I fpg_defines.inc}

interface

{ Register the stock HVIF icons into the global fpgIcons store.
  Called automatically by TfpgApplication.InternalInit. }
procedure fpgRegisterStandardIcons;

implementation

uses
  fpg_iconstore;

{ stdhvifimages.inc is generated by svg2hvif --inc.
  Until stock HVIF icons are available this include is intentionally empty. }
{$I stdhvifimages.inc}

procedure fpgRegisterStandardIcons;
begin
  { No stock HVIF icons registered yet.
    Application code may register its own icons via fpgIcons directly. }
end;

end.
