

  // The following colors match the predefined Delphi Colors
  // NOTE:
  //   The format is always RRGGBB (Red, Green, Blue);

  clAqua          = TfpgColor($00FFFF);
  clBlack         = TfpgColor($000000);
  clBlue          = TfpgColor($0000FF);
  clCream         = TfpgColor($FFFBF0);
  clDkGray        = TfpgColor($808080);
  clFuchsia       = TfpgColor($FF00FF);
  clGray          = TfpgColor($808080);
  clGreen         = TfpgColor($008000);
  clLime          = TfpgColor($00FF00);
  clLtGray        = TfpgColor($C0C0C0);
  clMaroon        = TfpgColor($800000);
  clNavy          = TfpgColor($000080);
  clOlive         = TfpgColor($808000);
  clPurple        = TfpgColor($800080);
  clRed           = TfpgColor($FF0000);
  clSilver        = TfpgColor($C0C0C0);
  clTeal          = TfpgColor($008080);
  clWhite         = TfpgColor($FFFFFF);
  clYellow        = TfpgColor($FFFF00);
  clNone          = TfpgColor($1FFFFFFF);
  clDefault       = TfpgColor($20000000);

  clMoneyGreen    = TfpgColor($C0DCC0);
  clSkyBlue       = TfpgColor($A6CAF0);
  clMedGray       = TfpgColor($A0A0A4);




  // System named color identifiers.  DON'T CHANGE THE ORDER!

  clWindowBackground    = $80000001;
  clBoxColor            = $80000002;
  clButtonFace          = $80000003;
  clShadow1             = $80000004;    // nice for disabled text
  clShadow2             = $80000005;
  clHilite1             = $80000006;
  clHilite2             = $80000007;
  clText1               = $80000008;    // normal text
  clText2               = $80000009;    // deep dark blue
  clText3               = $8000000A;    // red/brown
  clText4               = $8000000B;    // mud dark green
  clSelection           = $8000000C;
  clSelectionText       = $8000000D;
  clInactiveSel         = $8000000E;
  clInactiveSelText     = $8000000F;
  clScrollBar           = $80000010;
  clListBox             = $80000011;
  clGridLines           = $80000012;
  clGridHeader          = $80000013;
  clWidgetFrame         = $80000014;
  clInactiveWgFrame     = $80000015;
  clTextCursor          = $80000016;
  clChoiceListBox       = $80000017;
  clUnset               = $80000018;
  clMenuText            = $80000019;
  clMenuDisabled        = $8000001A;



  // De-facto NS & MSIE recognized HTML (web) color names
  // NOTE:
  //   The format is always RRGGBB (Red, Green, Blue);

  clAliceBlue           = TfpgColor($f0f8ff);
  clAntiqueWhite        = TfpgColor($faebd7);
  //clAqua              = TfpgColor($00ffff);
  clAquamarine          = TfpgColor($7fffd4);
  clAzure               = TfpgColor($f0ffff);
  clBeige               = TfpgColor($f5f5dc);
  clBisque              = TfpgColor($ffe4c4);
  //clBlack             = TfpgColor($000000);
  clBlanchedAlmond      = TfpgColor($ffebcd);
  //clBlue              = TfpgColor($0000ff);
  clBlueViolet          = TfpgColor($8a2be2);
  clBrown               = TfpgColor($a52a2a);
  clBurlyWood           = TfpgColor($deb887);
  clCadetBlue           = TfpgColor($5f9ea0);
  clChartreuse          = TfpgColor($7fff00);
  clChocolate           = TfpgColor($d2691e);
  clCoral               = TfpgColor($ff7f50);
  clCornflowerBlue      = TfpgColor($6495ed);
  clCornsilk            = TfpgColor($fff8dc);
  clCrimson             = TfpgColor($dc143c);
  clCyan                = TfpgColor($00ffff);
  clDarkBlue            = TfpgColor($00008b);
  clDarkCyan            = TfpgColor($008b8b);
  clDarkGoldenrod       = TfpgColor($b8860b);
  clDarkGray            = TfpgColor($a9a9a9);
  clDarkGreen           = TfpgColor($006400);
  clDarkKhaki           = TfpgColor($bdb76b);
  clDarkMagenta         = TfpgColor($8b008b);
  clDarkOliveGreen      = TfpgColor($556b2f);
  clDarkOrange          = TfpgColor($ff8c00);
  clDarkOrchid          = TfpgColor($9932cc);
  clDarkRed             = TfpgColor($8b0000);
  clDarkSalmon          = TfpgColor($e9967a);
  clDarkSeaGreen        = TfpgColor($8fbc8f);
  clDarkSlateBlue       = TfpgColor($483d8b);
  clDarkSlateGray       = TfpgColor($2f4f4f);
  clDarkTurquoise       = TfpgColor($00ced1);
  clDarkViolet          = TfpgColor($9400d3);
  clDeepPink            = TfpgColor($ff1493);
  clDeepSkyBlue         = TfpgColor($00bfff);
  clDimGray             = TfpgColor($696969);
  clDodgerBlue          = TfpgColor($1e90ff);
  clFireBrick           = TfpgColor($b22222);
  clFloralWhite         = TfpgColor($fffaf0);
  clForestGreen         = TfpgColor($228b22);
  //clFuchsia           = TfpgColor($ff00ff);
  clGainsboro           = TfpgColor($dcdcdc);
  clGhostWhite          = TfpgColor($f8f8ff);
  clGold                = TfpgColor($ffd700);
  clGoldenrod           = TfpgColor($daa520);
  //clGray              = TfpgColor($808080);
  //clGreen             = TfpgColor($008000);
  clGreenYellow         = TfpgColor($adff2f);
  clHoneydew            = TfpgColor($f0fff0);
  clHotPink             = TfpgColor($ff69b4);
  clIndianRed           = TfpgColor($cd5c5c);
  clIndigo              = TfpgColor($4b0082);
  clIvory               = TfpgColor($fffff0);
  clKhaki               = TfpgColor($f0e68c);
  clLavender            = TfpgColor($e6e6fa);
  clLavenderBlush       = TfpgColor($fff0f5);
  clLawnGreen           = TfpgColor($7cfc00);
  clLemonChiffon        = TfpgColor($fffacd);
  clLightBlue           = TfpgColor($add8e6);
  clLightCoral          = TfpgColor($f08080);
  clLightCyan           = TfpgColor($e0ffff);
  clLightGoldenrodYellow  = TfpgColor($fafad2);
  clLightGreen          = TfpgColor($90ee90);
  clLightGrey           = TfpgColor($d3d3d3);
  clLightPink           = TfpgColor($ffb6c1);
  clLightSalmon         = TfpgColor($ffa07a);
  clLightSeaGreen       = TfpgColor($20b2aa);
  clLightSkyBlue        = TfpgColor($87cefa);
  clLightSlateGray      = TfpgColor($778899);
  clLightSteelBlue      = TfpgColor($b0c4de);
  clLightYellow         = TfpgColor($ffffe0);
  //clLime              = TfpgColor($00ff00);
  clLimeGreen           = TfpgColor($32cd32);
  clLinen               = TfpgColor($faf0e6);
  clMagenta             = TfpgColor($ff00ff);
  //clMaroon            = TfpgColor($800000);
  clMediumAquamarine    = TfpgColor($66cdaa);
  clMediumBlue          = TfpgColor($0000cd);
  clMediumOrchid        = TfpgColor($ba55d3);
  clMediumPurple        = TfpgColor($9370db);
  clMediumSeaGreen      = TfpgColor($3cb371);
  clMediumSlateBlue     = TfpgColor($7b68ee);
  clMediumSpringGreen   = TfpgColor($00fa9a);
  clMediumTurquoise     = TfpgColor($48d1cc);
  clMediumVioletRed     = TfpgColor($c71585);
  clMidnightBlue        = TfpgColor($191970);
  clMintCream           = TfpgColor($f5fffa);
  clMistyRose           = TfpgColor($ffe4e1);
  clMoccasin            = TfpgColor($ffe4b5);
  clNavajoWhite         = TfpgColor($ffdead);
  //clNavy              = TfpgColor($000080);
  clOldLace             = TfpgColor($fdf5e6);
  //clOlive             = TfpgColor($808000);
  clOliveDrab           = TfpgColor($6b8e23);
  clOrange              = TfpgColor($ffa500);
  clOrangeRed           = TfpgColor($ff4500);
  clOrchid              = TfpgColor($da70d6);
  clPaleGoldenrod       = TfpgColor($eee8aa);
  clPaleGreen           = TfpgColor($98fb98);
  clPaleTurquoise       = TfpgColor($afeeee);
  clPaleVioletRed       = TfpgColor($db7093);
  clPapayaWhip          = TfpgColor($ffefd5);
  clPeachPuff           = TfpgColor($ffdab9);
  clPeru                = TfpgColor($cd853f);
  clPink                = TfpgColor($ffc0cb);
  clPlum                = TfpgColor($dda0dd);
  clPowderBlue          = TfpgColor($b0e0e6);
  //clPurple            = TfpgColor($800080);
  //clRed               = TfpgColor($ff0000);
  clRosyBrown           = TfpgColor($bc8f8f);
  clRoyalBlue           = TfpgColor($4169e1);
  clSaddleBrown         = TfpgColor($8b4513);
  clSalmon              = TfpgColor($fa8072);
  clSandyBrown          = TfpgColor($f4a460);
  clSeaGreen            = TfpgColor($2e8b57);
  clSeashell            = TfpgColor($fff5ee);
  clSienna              = TfpgColor($a0522d);
  //clSilver            = TfpgColor($c0c0c0);
  clSkyBlue2            = TfpgColor($87ceeb);
  clSlateBlue           = TfpgColor($6a5acd);
  clSlateGray           = TfpgColor($708090);
  clSnow                = TfpgColor($fffafa);
  clSpringGreen         = TfpgColor($00ff7f);
  clSteelBlue           = TfpgColor($4682b4);
  clTan                 = TfpgColor($d2b48c);
  //clTeal              = TfpgColor($008080);
  clThistle             = TfpgColor($d8bfd8);
  clTomato              = TfpgColor($ff6347);
  clTurquoise           = TfpgColor($40e0d0);
  clViolet              = TfpgColor($ee82ee);
  clWheat               = TfpgColor($f5deb3);
  //clWhite             = TfpgColor($ffffff);
  clWhiteSmoke          = TfpgColor($f5f5f5);
  //clYellow            = TfpgColor($ffff00);
  clYellowGreen         = TfpgColor($9acd32);

