

  // The following colors match the predefined Delphi Colors
  // NOTE:
  //   The format is always RRGGBB (Red, Green, Blue);
  
  clBlack         = TfpgColor($000000);
  clMaroon        = TfpgColor($800000);
  clGreen         = TfpgColor($008000);
  clOlive         = TfpgColor($808000);
  clNavy          = TfpgColor($000080);
  clPurple        = TfpgColor($800080);
  clTeal          = TfpgColor($008080);
  clGray          = TfpgColor($808080);
  clSilver        = TfpgColor($C0C0C0);
  clRed           = TfpgColor($FF0000);
  clLime          = TfpgColor($00FF00);
  clYellow        = TfpgColor($FFFF00);
  clBlue          = TfpgColor($0000FF);
  clFuchsia       = TfpgColor($FF00FF);
  clAqua          = TfpgColor($00FFFF);
  clLtGray        = TfpgColor($C0C0C0);
  clDkGray        = TfpgColor($808080);
  clWhite         = TfpgColor($FFFFFF);
  clCream         = TfpgColor($FFFBF0);
  clNone          = TfpgColor($1FFFFFFF);
  clDefault       = TfpgColor($20000000);

  clMoneyGreen    = TfpgColor($C0DCC0);
  clSkyBlue       = TfpgColor($A6CAF0);
  clMedGray       = TfpgColor($A0A0A4);
  
  
  
  
  // System named color identifiers.  DON'T CHANGE THE ORDER!
  
  clWindowBackground    = $80000001;
  clBoxColor            = $80000002;
  clButtonFace          = $80000003;
  clShadow1             = $80000004;
  clShadow2             = $80000005;
  clHilite1             = $80000006;
  clHilite2             = $80000007;
  clText1               = $80000008;
  clText2               = $80000009;
  clText3               = $8000000A;
  clText4               = $8000000B;
  clSelection           = $8000000C;
  clSelectionText       = $8000000D;
  clInactiveSel         = $8000000E;
  clInactiveSelText     = $8000000F;
  clScrollBar           = $80000010;
  clListBox             = $80000011;
  clGridLines           = $80000012;
  clGridHeader          = $80000013;
  clWidgetFrame         = $80000014;
  clInactiveWgFrame     = $80000015;
  clTextCursor          = $80000016;
  clChoiceListBox       = $80000017;
  clUnset               = $80000018;
  clMenuText            = $80000019;
  clMenuDisabled        = $8000001A;



