#
#   Makefile.fpc for fpGFX
#

[package]
name=fpgfx
version=0.3

[require]
packages=fcl-base

[target]
units=gfxbase geldirty gelimage
rsts=gfxbase
dirs_linux=x11
dirs_freebsd=x11
dirs_netbsd=xx11
dirs_win32=gdi

[compiler]
sourcedir=emulayer
unittargetdir=units
options=-S2h

[install]
buildunit=gfxbase
fpcpackage=y

[default]
fpcdir=/opt/fpc/src

[rules]
fpgfx$(PPUEXT): $(wildcard *.pas *.inc)

[libs]
libname=libfpgfx.so
libversion=0.3
