#
#   Makefile.fpc for fpGFX Win32 GDI support
#

[package]
name=fpgfx
version=0.3

[require]
packages=fcl
unitdir=.. ../emulayer

[target]
units=gfx_gdi gfxinterface
rst=gfx_gdi

[compiler]
unitdir=.. ../emulayer
unittargetdir=../units
options=-S2h

[install]
fpcpackage=y

[default]
fpcdir=/opt/fpc/src

#[libs]
#libname=fpgfx

#[install]
#subdir=

#[dirs]
#fpcdir=../../../..
#unitdir=..
